sonar.sources=src
sonar.exclusions=**/__tests__/**,**/e2e/**,**/*.test.ts,**/*.spec.ts,**/node_modules/**
sonar.tests=__tests__,e2e
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.typescript.tsconfigPath=tsconfig.json
